<?php
    defined('ABP01_LOADED') or die;
?>

<?php if ($data->info->exists || $data->track->exists): ?>
    <div id="abp01-techbox-teaser" class="abp01-techbox-teaser">
        <a id="abp01-techbox-teaser-action" href="javascript:void(0)"><?php echo __('Pentru firi pragmatice sau curioase există și un sumar tehnic al turei în josul paginii. Click aici pentru a-l consulta.'); ?></a>
    </div>
<?php endif; ?>