<?php
    defined('ABP01_LOADED') or die;
?>

<script type="text/javascript">
    var abp01_imgBase = '<?php echo $data->imgBaseUrl; ?>';
    var abp01_ajaxUrl = '<?php echo $data->ajaxUrl; ?>';
    var abp01_ajaxGetTrackAction = '<?php echo $data->ajaxGetTrackAction; ?>';

    var abp01_hasInfo = <?php echo $data->info->exists ? 'true' : 'false' ?>;
    var abp01_hasTrack = <?php echo $data->track->exists ? 'true' : 'false' ?>;
    var abp01_postId = <?php echo $data->postId; ?>;
    var abp01_nonceGet = '<?php echo $data->nonceGet; ?>';
</script>

<?php if ($data && ($data->info->exists || $data->track->exists)): ?>
    <div id="abp01-techbox-frontend" class="abp01-techbox-frontend">
        <div id="abp01-techbox-title" class="abp0-techbox-title">
            <span class="abp01-techbox-icon"></span><?php echo __('Trip summary') ?>
        </div>
        <div id="abp01-techbox-wrapper" class="abp01-techbox-wrapper">
            <?php if ($data->info->exists && $data->track->exists): ?>
                <ul id="abp01-techbox-tabs" class="abp01-techbox-tabs">
                    <li id="abp01-tab-info" class="abp01-tab abp01-tab-info <?php echo !$data->track->exists ? 'abp01-full-tab' : ''; ?>">
                        <a href="#abp01-techbox-info"><span class="dashicons dashicons-index-card"></span><?php echo __('Prosaic details') ?></a>
                    </li>
                    <li id="abp01-tab-map" class="abp01-tab abp01-tab-map <?php echo !$data->info->exists ? 'abp01-full-tab' : ''; ?>">
                        <a href="#abp01-techbox-map"><span class="dashicons dashicons-chart-line"></span><?php echo __('Map'); ?></a>
                    </li>
                </ul>
            <?php endif; ?>
            <div class="abp01-clear"></div>
            <div id="abp01-techbox-content" class="abp01-techbox-content">
                <?php if ($data->info->exists): ?>
                    <div id="abp01-techbox-info" class="abp01-techbox-info" style="<?php echo $data->track->exists ? 'display: none;' : ''; ?>">
                        <ul>
                            <?php if ($data->info->isBikingTour): ?>
                                <?php displayInfoItem($data, 'bikeDistance', 'Distanța totală', 'km'); ?>
                                <?php displayInfoItem($data, 'bikeTotalClimb', 'Diferența de nivel', 'm'); ?>
                                <?php displayInfoItem($data, 'bikeDifficultyLevel', 'Nivel de dificultate', ''); ?>
                                <?php displayInfoItem($data, 'bikeAccess', 'Acces', ''); ?>
                                <?php displayInfoItem($data, 'bikeRecommendedSeasons', 'Practicabil în sezoanele', ''); ?>
                                <?php displayInfoItem($data, 'bikePathSurfaceType', 'Suprafața drumului', ''); ?>
                                <?php displayInfoItem($data, 'bikeBikeType', 'Tip recomandat de bicicletă', ''); ?>
                            <?php elseif ($data->info->isHikingTour): ?>
                                <?php displayInfoItem($data, 'hikingDistance', 'Distanța totală', 'km'); ?>
                                <?php displayInfoItem($data, 'hikingTotalClimb', 'Diferența de nivel', 'm'); ?>
                                <?php displayInfoItem($data, 'hikingDifficultyLevel', 'Nivel de dificultate', ''); ?>
                                <?php displayInfoItem($data, 'hikingAccess', 'Acces', ''); ?>
                                <?php displayInfoItem($data, 'hikingRecommendedSeasons', 'Practicabil în sezoanele', ''); ?>
                                <?php displayInfoItem($data, 'hikingSurfaceType', 'Suprafața drumului/potecii', ''); ?>
                                <?php displayInfoItem($data, 'hikingRouteMarkers', 'Marcaje', ''); ?>
                            <?php elseif ($data->info->isTrainRideTour): ?>
                                <?php displayInfoItem($data, 'trainRideDistance', 'Distanța totală', 'km'); ?>
                                <?php displayInfoItem($data, 'trainRideChangeNumber', 'Trenuri schimbate', ''); ?>
                                <?php displayInfoItem($data, 'trainRideGauge', 'Ecartament', ''); ?>
                                <?php displayInfoItem($data, 'trainRideOperator', 'Operatori utilizați', ''); ?>
                                <?php displayInfoItem($data, 'trainRideLineStatus', 'Status linie', ''); ?>
                                <?php displayInfoItem($data, 'trainRideElectrificationStatus', 'Status electrificare', ''); ?>
                                <?php displayInfoItem($data, 'trainRideLineType', 'Tip linie'); ?>
                            <?php endif; ?>
                        </ul>
                    </div>
                <?php endif; ?>
                <?php if ($data->track->exists): ?>
                    <div id="abp01-techbox-map" class="abp01-techbox-map" style="<?php echo $data->info->exists ? 'display: none;' : ''; ?>">
                        <div id="abp01-map-container" class="abp01-map-container" data-role="map-container">
                            <div id="abp01-map" class="abp01-map" data-role="map-holder"></div>
                        </div>
                    </div>
                <?php endif; ?>
            </div>
            <div id="abp01-techbox-content-skip-teaser" class="abp01-techbox-content-skip-teaser" style="display: none;">
                <a id="abp01-techbox-content-skip-teaser-action" href="javascript:void(0)"><?php echo __('Se pare că ai sărit peste poveste. E păcat să o ratezi. Nu ai vrea să o citești? Click aici pentru început!'); ?></a>
            </div>
        </div>
    </div>
<?php endif; ?>